### ISSUE TITLE
How to have it not animate but jump immediately?

### ISSUE THREAD

**Issue by ianstormtaylor** [KoryNunn/scroll-into-view#10]
I'd like to remove the animation completely and have it jump to the spot immediately. I've tried:
- `time: 0`
- `ease: value => 1`
- `ease: value => 0`

But none of those seem to work. Thanks!

**Comment by KoryNunn** [comment]
Resolved in v1.7.1 which is now published.

**Comment by alexisargyris** [comment]
I tried ```time: 0``` and it is still scrolling very visibly. Can you please spell out what is the recommended way of jumping immediately (i.e. no animation)? Maybe it might merit a mention in the readme. Thanks a lot, great utility!

**Comment by KoryNunn** [comment]
@alexisargyris 

```
scrollIntoView(target, { time: 0 });
```

Should, in all cases, complete within 1 frame.

I have added a test for this, and it works consistently for single depth targets, but in some cases, when you have a large number of nested scrolling regions, it occasionally does not complete in the correct location, which I'll have to fix.

**Comment by alexisargyris** [comment]
You guessed right. This is exactly my case, I’m afraid.

**Comment by KoryNunn** [comment]
Hi, just an update, I haven't gotten around to this because I've been lazy and it's not super easy.
