### ISSUE TITLE
Breaking change hidden in minor version bump [1.16.0]

### ISSUE THREAD

**Issue by RookY2K** [KoryNunn/scroll-into-view#100]
Hello,

So first off, this isn't meant to be a gripe, rant, or any sort of post of entitlement. Just a bit of constructive criticism.

Unfortunately, for at least the next 6 months, my company has to support IE11. This is obviously not your problem and I fully understand dropping support for that zombie browser. 

However, what I think could have been done better is releasing this change as a breaking *Major* release so that it wouldn't have caught consumers of this fine library with their proverbial pants down. 

Thanks for your time developing this library. It is much appreciated!

**Comment by KoryNunn** [comment]
Fair enough. I honestly didn't know I was dropping IE support, it just accidentally worked on IE before that release.

Browser support is listed in the README now, so it will be considered for future releases.
