### ISSUE TITLE
Scrolling does not work correctly in XHTML documents

### ISSUE THREAD

**Issue by robertknight** [KoryNunn/scroll-into-view#101]
When `scrollIntoView` ascends the element tree it tests the `tagName` property of elements to work out when it has reached the `<body>`:

https://github.com/KoryNunn/scroll-into-view/blob/2a3c18aa1129e36e35f198cd12c2a3ba0e20a4f2/scrollIntoView.js#L202

In an XHTML document ([example](https://www.w3.org/People/mimasa/test/xhtml2/spec-examples/)) `document.body.tagName` returns "body" rather than "BODY" as it does in HTML documents. See [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/Element/tagName).

The result is that the test incorrectly fails and the document is scrolled to the wrong location. In some limited testing, making the test case insensitive appears to resolve the issue.

**Comment by KoryNunn** [comment]
Published as 1.16.2, sorry I didn't get around to it sooner.
