### ISSUE TITLE
A suspicious line in the code

### ISSUE THREAD

**Issue by cie** [KoryNunn/scroll-into-view#11]
Hello,

First, thanks for this amazing, "just-works" package!

There is a line in the code which I'm a bit concerned about, not because it causes any problems but I'm not sure what's the intention behind it.

Here:

        if(
            settings.validTarget ? settings.validTarget(parent, parents) : true &&
            parent === window ||
            (
                parent.scrollHeight !== parent.clientHeight ||
                parent.scrollWidth !== parent.clientWidth
            ) &&
            getComputedStyle(parent).overflow !== 'hidden'
        )

The first line seems to be meant to be in parenthesis:

        if(
            (settings.validTarget ? settings.validTarget(parent, parents) : true) &&
            parent === window ||
            (
                parent.scrollHeight !== parent.clientHeight ||
                parent.scrollWidth !== parent.clientWidth
            ) &&
            getComputedStyle(parent).overflow !== 'hidden'
        )

otherwise the `ture &&` would be a no-op, and the logic in the other lines would be overruled by `validTarget`. And i think also the other lines need to be parenthesised, otherwise the `validTarget` function would have no effect unless `parent === window`:

        if(
            (settings.validTarget ? settings.validTarget(parent, parents) : true) &&
            (parent === window ||
                (
                    parent.scrollHeight !== parent.clientHeight ||
                    parent.scrollWidth !== parent.clientWidth
                ) &&
                getComputedStyle(parent).overflow !== 'hidden'
            )
        )

But maybe I'm getting it wrong.

Thanks!

**Comment by cie** [comment]
Oh, and maybe I got the wording wrong but I didn't think of any bad intentions behind it, I guess it's a mistake :)

**Comment by KoryNunn** [comment]
I agree this bit of code is very confusing to read, but it does work as intended, if not by the same mechanics as you would hope. I'll improve readability.

**Comment by KoryNunn** [comment]
I've pushed the changes to master, but haven't published as there is no functional difference.

Remember, && has a higher precedence than ||.

**Comment by jraoult** [comment]
@KoryNunn following my comment here: https://github.com/KoryNunn/scroll-into-view/commit/c2148af080fc91cdf015fc54d9a31c9761c767b0#commitcomment-20850168 I think this is the issue responsible for this change.

I think that by "improving" readability you changed the behavior. Ternary operator precedence rule is a little counterintuitive so you changed something that was interpreted:

```
 settings.validTarget ? settings.validTarget(parent, parents) :  (true && ...
```
to
```
(settings.validTarget ? settings.validTarget(parent, parents) : true) && ...
```

**Comment by KoryNunn** [comment]
Yep, the old code skipped checks that it shouldn't have, which could have caused issues that we never ran into in realworld usage. See your issue for description.

**Comment by KoryNunn** [comment]
Actually can you open a proper issue for your experiences in angular so I have something to refer to?
