### ISSUE TITLE
It does not work in IE 11

### ISSUE THREAD

**Issue by frankfu03** [KoryNunn/scroll-into-view#13]

**Comment by KoryNunn** [comment]
Damn.

I don't have a windows PC to fix it on, or a requirement for it to work in IE11, feel free to submit a PR.

**Comment by musicformellons** [comment]
This helps?:
https://www.npmjs.com/package/ie11-scroll-into-view

**Comment by KoryNunn** [comment]
Closing due to lack of information, confirmation, or response.
