### ISSUE TITLE
Support for element in <iframe>?

### ISSUE THREAD

**Issue by lichaozhy** [KoryNunn/scroll-into-view#15]
I can't make it support to scroll a element in <iframe> easily. Could you provide some solution for it?

**Comment by KoryNunn** [comment]
This is outside the concern of this tool, but may be doable in your project.

To achieve this, you would need ownership of the domain that the iframe references, if you have that, you could use the (postMessage)[https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage] API to tell the child frame where to scroll, and use scroll-into-view inside that frame.
