### ISSUE TITLE
weird target issues in validTarget callback

### ISSUE THREAD

**Issue by johnstew** [KoryNunn/scroll-into-view#19]
So I currently have a callback that looks like this.
```js
validTarget: function(target, parentsScrolled){
    return parentsScrolled < 2 && target.classList.contains('sidebar__wrapper');
}
```

Then I have some html that looks like this.

```html
<nav class="sidebar">
    <div class="sidebar__wrapper">
        <ul class="sidebar__list">
            <li class="sidebar__list__item"></li>
                         ....
        </ul>
    </div>
</nav>
```
For some reason I keep getting `Cannot read property 'contains' of undefined` which is weird because target is a valid HTMLElement and has classList as a property. Is target not an HTMLElement?

**Comment by KoryNunn** [comment]
You can see what `target` is by using `console.log(target)` to look at it.

If you do so, you will see that the last `target` you will be passed will be `window`, since it is the top-most scroll-able element.
