### ISSUE TITLE
firefox doesn't scroll to element when using absolute positioning

### ISSUE THREAD

**Issue by LaurieSReynolds** [KoryNunn/scroll-into-view#20]
Scrolling to a row (tr) in a table which is embedded in a div.....  
~ Firefox always scrolls to the top.    
~ Chrome and Safari work beautifully.

Adding an offset to the following values fixes the problem - obviously not a solution.

document.body.scrollHeight 
~ chrome = 2175
~ firefox = 81

window.scrollY
~chrome = 1372
~ firefox = 0

~~~~~~~~~~~~~~
Version: 1.7.4
Node: 6.9.5
Computer:  Mac

Framework:  React +  (custom css layout)

Usage - where element is a tr
scrollIntoView(element, {
        align: {
          top: 0.5,
          left: 1
        }
      });

~~~~~~~~~~~~~~~~~~~~~
console.log for firefox

========= NOT WINDOW =================  bundle.js:94637:9
DOMRect { x: -224, y: 0, width: 776, height: 81, top: 0, right: 552, bottom:
81, left: -224 }  bundle.js:94639:9
~~~~~~~~~~  bundle.js:94656:5
Object { x: 248, y: 0, differenceX: 248, differenceY: 0 }  bundle.js:94657:5
DOMRect { x: 0, y: 2047, width: 800, height: 30, top: 2047, right: 800, bottom:
2077, left: 0 }  bundle.js:94620:9
window.scrollX =  224  bundle.js:94621:9
window.scrollY =  0  bundle.js:94622:9
window.innerWidth =  776  bundle.js:94623:9
window.innerHeight =  841  bundle.js:94624:9
document.body.scrollWidth =  1024  bundle.js:94625:9
document.body.scrollHeight =  81  bundle.js:94626:9
========= NOT WINDOW =================  bundle.js:94637:9
DOMRect { x: -224, y: 0, width: 1024, height: 0, top: 0, right: 800, bottom: 0,
left: -224 }  bundle.js:94639:9
~~~~~~~~~~  bundle.js:94656:5
Object { x: 0, y: 81, differenceX: 0, differenceY: 81 }  bundle.js:94657:5
))))
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
console.log out for Chrome...

crollIntoView.js:43 ========= NOT WINDOW =================
scrollIntoView.js:45 ClientRect {top: -1372, right: 463, bottom: -1291, left: -224, width: 687…}
scrollIntoView.js:62 ~~~~~~~~~~
scrollIntoView.js:63 Object {x: 337, y: 0, differenceX: 337, differenceY: 0}
scrollIntoView.js:26 ClientRect {top: 675, right: 800, bottom: 705, left: 0, width: 800…}
scrollIntoView.js:27 window.scrollX =  224
scrollIntoView.js:28 window.scrollY =  1372
scrollIntoView.js:29 window.innerWidth =  687
scrollIntoView.js:30 window.innerHeight =  803
scrollIntoView.js:31 document.body.scrollWidth =  1024
scrollIntoView.js:32 document.body.scrollHeight =  2175
scrollIntoView.js:35 ========= WINDOW =================
scrollIntoView.js:62 ~~~~~~~~~~
scrollIntoView.js:63 Object {x: 224, y: 1660.5, differenceX: 0, differenceY: 288.5}

**Comment by KoryNunn** [comment]
Hi, thanks for the issue. Would you be able to provide a simple reproduction file for this?

**Comment by LaurieSReynolds** [comment]
It's using a lot of custom code - I'll see if I can reproduce it with a really basic table and post a link.

**Comment by LaurieSReynolds** [comment]
I created a small example project that demonstrates the problem.  Looks like it is a problem with setting one of the divs as position: absolute.

https://github.com/LaurieSReynolds/scroll-firefox-bug

Let me know if you have trouble running/seeing the problem.

**Comment by KoryNunn** [comment]
Ok I've figured out the problem.

firefox doesn't account for the height of absolutely positioned elements in it's window.scrollHeight. This may or may not be valid, but it's a problem for scroll-into-view. I will look at what I can do for this, but the answer may very well be "I can't help you, don't absolutely position content that you want to scroll to" :/.

The scrolling to top issue is unrelated to scroll-into-view, and if you comment out the scroll-into-view call in your example, it scrolls to the top.

PS: I hate firefox with a passion, using the debugger is a horrible, painful experience.

**Comment by LaurieSReynolds** [comment]
Thanks for investigating so quickly.   Understand - nothing you can do - seems like a Firefox quirk.  Totally agree - Sadly, print statements are more productive than using the Firefox debugger.

**Comment by KoryNunn** [comment]
I'd suggest looking into why your page scrolls to the top when you click a row, removing that will at least prevent the bad user experience.

**Comment by LaurieSReynolds** [comment]
Good point.  I'll take a look.  For the example, I artificially added a scroll to top.  In our application, there are two paths to getting

**Comment by KoryNunn** [comment]
Hi @LaurieSReynolds can you please test again with the latest version of scroll-into-view, this may have been fixed by #21

**Comment by KoryNunn** [comment]
Nvm I tested it, it doesn't fix FF :(

**Comment by LaurieSReynolds** [comment]
Thanks for the update.   I gave it a try and got the same result as you.

**Comment by KoryNunn** [comment]
Hi @LaurieSReynolds would you be able to re-check your use-case against the latest changes, there have been a few firefox specific fixes lately.

**Comment by LaurieSReynolds** [comment]
Wonderful!   Looks like it is fixed!

Used this repo - doesn't work with 1.7.4, but works great with version 1.9.0
https://github.com/LaurieSReynolds/scroll-firefox-bug

Thank you!

**Comment by KoryNunn** [comment]
Awesome, thanks for checking that.

**Comment by abhishek-udataneni** [comment]
I had a weird issue with scrollIntoView. It was working perfectly on crome and edge but mozilla it was behaving weirdly.I had to remove the object {behaviour: smooth} from the options.It started working.Might help someone else here.

**Comment by KoryNunn** [comment]
@abhishek-udataneni I think you're talking about the native browser scrollIntoView function, which is not used by, and solves a different problem to, this module.
