### ISSUE TITLE
Option to scroll target to fixed offset on screen

### ISSUE THREAD

**Issue by ericvrp** [KoryNunn/scroll-into-view#25]
I have a 40px appbar and If I scroll to a section this package puts the top 40 pixels of the element behind the appbar. To solve this and have my section immidiately below the appbar I have put 'y -= 40;' before both occurances of 'differenceX = x - '... in scrollIntoView.js .

Is there a way to do what I want without editing your code?

**Comment by KoryNunn** [comment]
You should be able to use the align option to achieve this:

```
scrollIntoView(someElement, {
    align:{
        top: (some math here that calculates the offset value)
    }
});
```

**Comment by ericvrp** [comment]
That was my first guess. But either that does not work as intended or I do not understand the docs.

**Comment by KoryNunn** [comment]
So the value is where to align the element relevant to the viewport, where 0 is fully top/left, and 1 is fully bottom/right.

The logic is implemented here: https://github.com/KoryNunn/scroll-into-view/blob/master/scrollIntoView.js#L14

You should be able to calculate what value of your viewport 40px is by doing `1 / window.innerWidth * 40` and set that as the left align.

Without seeing your exact use case I can't really help much more.

**Comment by ericvrp** [comment]
So by default the target should be centered just like http://korynunn.github.io/scroll-into-view/example/  ? My site http://nieuw.be-water.nl scrolls a section to the top by default. What could I be doing wrong?

**Comment by ericvrp** [comment]
On the developer console you can try scrollIntoView(document.getElementById('opleidingen')) and you will see that that section does not get centered in the middle of the screen. 

Please note that in this version I screen to y+40 and I noticed that in my development build of this React 'app'/site the scrolling seems top ignore the alignment completely.

**Comment by KoryNunn** [comment]
The scrolling in http://nieuw.be-water.nl looks to be working perfectly for me, the target section scrolls to as close to the centre as it can, unless it is too big to fit into the UI, in which case it aligns to the top of the viewport. What behaviour are you seeing?

**Comment by ericvrp** [comment]
It looks like I am seeing the same as you but it was not what I expected. What I thought it would do is always the same: i.e. scroll the top-left pixel of my target to the top,left align settings.

**Comment by KoryNunn** [comment]
Oh ok, I might try and explain the behaviour a little better in the read me.

Does this resolve this issue tho?

**Comment by ericvrp** [comment]
Thank you very much! I'm still not sure if I can do what I would like. I have the feeling we need two things for alignment.
1. The targetlocation (x%,y%) in target element.
2. the screenlocation  we would like to have the target element location anchored to.

**Comment by KoryNunn** [comment]
I'm still not 100% sure what you're after, would you be able to send a PR for either the implementation, or documentation I could use to implement it from?

**Comment by KoryNunn** [comment]
Hopefully the latest version resolves this for you.
