### ISSUE TITLE
Ignores top alignment if top offset not given

### ISSUE THREAD

**Issue by adamreisnz** [KoryNunn/scroll-into-view#30]
Finally a real bug.

These lines are problematic:

```
leftOffset = align && align.leftOffset !== null ? align.leftOffset : 0,
topOffset = align && align.topOffset !== null ? align.topOffset : 0,
```

If you specify alignment options only containing a `top` value, it will not work (doesn't scroll at all). Only after you add `topOffset: 0` explicitly does it work again.

I suggest the above lines are altered to something like:

```
leftOffset = align && typeof align.leftOffset === 'number' ? align.leftOffset : 0,
topOffset = align && typeof align.topOffset === 'number' ? align.topOffset : 0,
```

That way they will default to 0 if the option is not provided.

**Comment by KoryNunn** [comment]
That's no different as long as you don't pass non-numbers to the call. What's the configuration you are using?

**Comment by KoryNunn** [comment]
Here it is working in the example: https://github.com/KoryNunn/scroll-into-view/blob/master/example/index.js#L29

**Comment by adamreisnz** [comment]
I am passing `undefined`, because I am not defining the property at all, and the original code then leaves this as `undefined` because `undefined` does not equal `null`. This then stops the scroll from working, until I explicitly pass `0`.

Maybe the examples use simplistic non-real world HTML, I don't know. Also, my problem was with `top: 1` not `top: 0`. That could affect it as well.

This is the full config passed:

```
        time: 250,
        align: {
          top: 1,
        },
        validTarget(target, parentsScrolled) {
          return (
            parentsScrolled < 2 && target !== window &&
            !target.matches('.modal')
          );
        },
```

**Comment by KoryNunn** [comment]
The code in the source is 
```
leftOffset = align && align.leftOffset != null ? align.leftOffset : 0,
        topOffset = align && align.topOffset != null ? align.topOffset : 0,
```

Are you installing this from NPM? Which version?

**Comment by adamreisnz** [comment]
I copied your code from the github repo, because I can't run the package in the browser due to the way that you've included `require('raf')` and my build process doesn't cater for requires, so I get a `require` is undefined error.

It seems after copying, my linter fixed your `!=` comparison to `!==` because that's best practice for javascript. (E.g. null !== undefined). Probably in your version it doesn't care due to the `!=`.

**Comment by KoryNunn** [comment]
Ok so this is an issue with your build process.

!= null is a perfectly reasonable way to check something is neither undefined or null.

I'd suggest you build this module with broeserif

**Comment by adamreisnz** [comment]
I'm sorry, but I think you're being somewhat short sighted -- my build process is perfectly fine, and it's been used in many commercial projects. it's the way you package this repository is problematic, because it can't be consumed by different build processes. Not everyone uses browserify, nor wants to use browserify, so you can't force it on people. The right way to go about it is to pre-build a standalone JS file that can be included by *any* build process/browser and will work right off the bat. 

Consumers of this script don't care how you built your package, or what build tools they need to get it up and running, or whether or not it's written in TypeScript or ES6 or ES3. They just want to include it and run it, and you as package developer should provide that option or you will alienate a large user base.

**Comment by KoryNunn** [comment]
Pull requests welcome.

**Comment by KoryNunn** [comment]
@adamreisnz I created a minified version after a polite request in issue #32
