### ISSUE TITLE
[Violation] Added non-passive ???

### ISSUE THREAD

**Issue by HaveF** [KoryNunn/scroll-into-view#31]
Hi, thanks for this repo first.

I use it(1.8.0 chrome  60.0.3099.0 canary ) in a very easy case like this:
```js
                          scrollIntoView(document.querySelectorAll('h1')[0], {
                            time: 200,
                          })
```
And the console complains like this:
<img width="736" alt="2017-06-01 5 14 02" src="https://cloud.githubusercontent.com/assets/54462/26672979/cd5f790a-46ed-11e7-9bfa-4dbaf93593f5.png">

```
scrollIntoView.js:123 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.
transitionScrollTo @ scrollIntoView.js:123
module.exports @ scrollIntoView.js:177
onClick @ App.js:112
ReactErrorUtils.invokeGuardedCallback @ ReactErrorUtils.js:69
executeDispatch @ EventPluginUtils.js:85
executeDispatchesInOrder @ EventPluginUtils.js:108
executeDispatchesAndRelease @ EventPluginHub.js:43
executeDispatchesAndReleaseTopLevel @ EventPluginHub.js:54
forEachAccumulated @ forEachAccumulated.js:24
processEventQueue @ EventPluginHub.js:257
runEventQueueInBatch @ ReactEventEmitterMixin.js:17
handleTopLevel @ ReactEventEmitterMixin.js:28
handleTopLevelImpl @ ReactEventListener.js:72
perform @ Transaction.js:140
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
batchedUpdates @ ReactUpdates.js:97
dispatchEvent @ ReactEventListener.js:147
```

what can I do now? thanks

**Comment by KoryNunn** [comment]
This is just a warning saying that the browser will need to block scrolling until the code run by the handler is complete, incase it calls `event.preventDefault()`. It will not affect your application.

I'll consider adding in the passive flag when it is supported in all browsers:

http://caniuse.com/#feat=passive-event-listener

**Comment by AntonTrollback** [comment]
Okay then :)
It's now supported in the latest version of all major browsers.

**Comment by KoryNunn** [comment]
Ok I'd be happy to add this. Should get around to it in the near future, just a bit busy at the moment.

Alternatively @HaveF or @AntonTrollback Pull request welcome ;)
