### ISSUE TITLE
scroll-into-view doesn't work within iframes

### ISSUE THREAD

**Issue by RobertHodan** [KoryNunn/scroll-into-view#33]
When scroll-into-view is used within an iframe, it doesn't scroll to the specified element.

There's a function called isScrollable that checks if the parent === window. The parent in this case refers to the the parent of the iframe's window, and so this function always returns false. For example, lets say I have a iframe that points to frame.html, and this is used in index.html. I choose to scroll to a paragraph, and so isScrollable is called several times:
```
Call 1:
    element parameter: <p>...</p>
    parent href: "index.html"
    window href: "frame.html"
Call 2:
   element parameter: <div>...</div>
   parent href: "index.html"
   window href: "frame.html"
Call 3:
   element parameter: Window (href: "frame.html")
   parent href: "index.html"
   window href: "frame.html"
```

On all 3 calls, the parent is compared with the window. Simply changing the check to element === window fixes this issue, since it eventually gets to the iframe element.

**Comment by KoryNunn** [comment]
Hi, the comparison of parent to window was a mistake from a refactor. I've updated to use element instead.

Please give it a go and let me know if it is resolved.

**Comment by RobertHodan** [comment]
It's resolved now, thank you so much!
