### ISSUE TITLE
How should I setup that only if the dom is invisible then to scroll?

### ISSUE THREAD

**Issue by HaolinWang8** [KoryNunn/scroll-into-view#40]
I am make a grid using this package. I am wondering is that a way only if I am almost at the edge of window so that trigger the scroll into view?

**Comment by KoryNunn** [comment]
Do you want to scroll only if the element you want in view is somewhat obscured by a parent?

You could check if the element is obscured first, then trigger the scroll if it is.

I have a module for checking how much of an element is exposed: http://npmjs.com/package/predator

Let me know if that solves your problem.

**Comment by KoryNunn** [comment]
I'm assuming this issue is either resolved or no longer needed, so I'm going to close it.

It can be opened again if the question was not answered adequately.
