### ISSUE TITLE
Naming? 

### ISSUE THREAD

**Issue by kosso** [KoryNunn/scroll-into-view#44]
This might need to be renamed since `scrollIntoView()` exists already:

http://caniuse.com/#search=scrollIntoView 
https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView

**Comment by KoryNunn** [comment]
I'm not worried, anyone using this module is most likely after the deep alignment functionality, and is likely not going to use element.scrollIntoView anyway.
