### ISSUE TITLE
Always scrolling?

### ISSUE THREAD

**Issue by srinivasvenigalla** [KoryNunn/scroll-into-view#48]
@here How do I make this scroll only when needed? Right now, as I tab across the page, it tries to move every focusable element into view and make the screen jumpy.. I am using default function, with no options.

**Comment by KoryNunn** [comment]
Can you do a reproduction? how are you calling the function? I'm guessing you might be overlapping scroll requests, making them fight eachother.

**Comment by KoryNunn** [comment]
Closing due to lack of response/reproduction.
