### ISSUE TITLE
Only works with an element with a parent

### ISSUE THREAD

**Issue by melisiweb** [KoryNunn/scroll-into-view#50]
Hi,
thanks for the great library!

I spot a small bug: if i try to scroll to an element whose parent is the body tag, the scrolling still happens but it doesn't stop to that element, it goes to the bottom of the page. Not sure if this was intended

**Comment by KoryNunn** [comment]
Hi @melisiweb would you be able to send a pull request with this failing case added to the tests?

**Comment by KoryNunn** [comment]
Closing since stale and not reproducible.
