### ISSUE TITLE
ScrollIntoView is not working in tab portrait mode

### ISSUE THREAD

**Issue by rakesh0r** [KoryNunn/scroll-into-view#53]
ScrollIntoView is not working in samsung tab portrait mode

**Comment by KoryNunn** [comment]
Hi, Thanks for the report, but I have no way to test this, as I don't have access to a galaxy tab.

@rakesh0r what scenarios are you running that do not work? Does the [example page](http://korynunn.github.io/scroll-into-view/example/) work?

If someone feels like looking into this, that'd be great.

**Comment by KoryNunn** [comment]
Closing since stale and no response.
