### ISSUE TITLE
getComputedStyle() not available in IE (versions < 9)

### ISSUE THREAD

**Issue by Sysdevcode** [KoryNunn/scroll-into-view#54]
When using the function with IE (earlier versions < 9), then getComputedStyle() style is not available, to overcome this I use <code>element.currentStyle</code> which I incorporated into a function <code>computedStyle()</code> function (listed below) instead to get the style.   

```` javascript

function computedStyle(el, prop, getComputedStyle, style) {
    getComputedStyle = window.getComputedStyle;
    style =
        // If we have getComputedStyle
        getComputedStyle 
            ? getComputedStyle(el)        // Query it
            : el.currentStyle;                    // Otherwise, we are in IE and use currentStyle
    if (style) {
        return style
        [
            // Switch to camelCase for CSSOM - Grabbed from jQuery
            // https://github.com/jquery/jquery/blob/1.9-stable/src/css.js#L191-L194
            prop.replace(/-(\w)/gi, function (word, letter) {
                return letter.toUpperCase();
            })
        ];
    }
}

````

So I changed you line function:

```` javascript
function defaultIsScrollable(element){
         ...
        getComputedStyle(element).overflow !== 'hidden'
       ...
}
````
to 
```` javascript
function defaultIsScrollable(element){
         ...
        computedStyle(element, 'overflow') !== 'hidden'
        ...
}
`````

The same issue occurs with the <code>addEventListener()</code>, which I replaced with <code>attachEvent('on' + event, ...)</code>.

Not sure if you want to incorporate these or not, just thought I would say thanks and these are the changes I made to make the function work with more compatibility.

Thanks

**Comment by KoryNunn** [comment]
Hi, thanks for pointing this out.

At this point, due to the extremely small usage statistics on IE's<9 I'm not going to support them in this project speifically.

However, these issues can easily be fixed by polyfilling the missing API's for older browser, polyfill.io is an easy way to do this.

Closing for now, please feel free to re-open/comment if you feel there is more to be discussed.
