### ISSUE TITLE
Causes page to scroll when modal is open

### ISSUE THREAD

**Issue by louisgjohnson** [KoryNunn/scroll-into-view#55]
I've got an issue where I have a custom modal open and the body is set to `overflow: none;` but the package still causes the page to scroll and the modal

**Comment by KoryNunn** [comment]
Did you mean to use `overflow: hidden;`?

That case is handled in this module.
https://github.com/KoryNunn/scroll-into-view/blob/master/scrollIntoView.js#L150

**Comment by KoryNunn** [comment]
`none` is not a valid value for `overflow`: https://developer.mozilla.org/en-US/docs/Web/CSS/overflow

**Comment by KoryNunn** [comment]
@louisgjohnson was this the issue? I'll close this if it's resolved.

**Comment by louisgjohnson** [comment]
Maybe I've implemented something incorrectly then, I've got `overflow: hidden` on the body element but there's a div that has `height: 100%` which is what causes the scrolling

**Comment by louisgjohnson** [comment]
@KoryNunn Yeah that fixed the issue, thank you!

**Comment by KoryNunn** [comment]
Awesome glad it's resolved.
