### ISSUE TITLE
Horizontal scrolling problem inside a div

### ISSUE THREAD

**Issue by rvalitov** [KoryNunn/scroll-into-view#56]
Hi! Thank you for this library, it looks what I need, but it does not work in my case. The description is below.

# Problem Overview
I use [Puppeteer](https://github.com/GoogleChrome/puppeteer) to load web pages and take screenshots of some elements on the page. Usually the elements I need are not visible after a page load, so I need to scroll them into view. I was using [`element.scrollIntoView`](https://developer.mozilla.org/en/docs/Web/API/Element/scrollIntoView) function and it was working good, but I found a web page, where it did nothing and was useless. Therefore, I decided to try your function. Unfortunately, it didn't work, too.

# Problem Details
There's a web page https://myspace.com/dubaidancestudio
After a page load it looks like this:

![image](https://user-images.githubusercontent.com/16267156/51858025-c9afca00-2344-11e9-8c9d-89c546d1d3fa.png)

I have an element which is located on the right side of the page and which is not originally visible, it's `<a>` tag with text "Show more" marked red:

![image](https://user-images.githubusercontent.com/16267156/51858142-054a9400-2345-11e9-97d7-2ff2e42e9e1a.png)

It has a selector `#stream > li:nth-child(7) > article > div > span > a` (I grab the selectors by using the right mouse click in the Chrome browser).  I want to scroll the parent `div` to this element, so that it comes into view.

# Test scenario
To make things simple Puppeteer can be considered as a standard Google Chrome browser. Actually technically it does not matter if I use Puppeteer or not. I wrote about Puppeteer above, so that you have a right understanding why I need to scroll.

Below I describe how I made a test in a standard Chrome version 71.0.3578.98 (64 bit), so the problem happens in a standard browser, too. It is not related to Puppeteer in any way.

First I opened developer's console and injected the minified JS code of yours:

![image](https://user-images.githubusercontent.com/16267156/51858341-8f92f800-2345-11e9-872d-3e60e65a88d2.png)

After that the `window.scrollIntoView` function becomes available. Then I try to scroll by calling

```js
window.scrollIntoView(document.querySelector('#stream > li:nth-child(7) > article > div > span > a'));
```

But it does not work as expected and behavior depends on the current position of horizontal scroller:

- If scroller has initial position, then the function has no effect. 
- If scroller is moved a little right, then after function call it scrolls left to initial position instead of scrolling right to the element
- If scroller is moved a lot to the right so that the element is almost visible, then after function call it scrolls correctly to the element.

I tried with different elements on this page but still have the same results. I also captured a screencast of my actions, please, have a look here: https://youtu.be/6YIjJKEjViY

I would appreciate if you can help me with this issue. Am I doing something wrong? Any help and ideas are welcome! Thank you in advance!

**Comment by KoryNunn** [comment]
Hi, the element you are attempting to scroll to is inside an `<li>` with a class `.hiddenOffScreen`, which has a CSS rule:

```
.hiddenOffScreen > *{
    display: none;
}
```

This makes scrollIntoView default to `0,0`, which is why it scrolls to the top left, but if you scroll far enough to the right, it will remove that class, and work.

You can 'fix' this for your case with the following code:

```javascript
var style = document.createElement('style');

style.textContent = ".hiddenOffScreen>*{ display: initial !important;}"

document.body.appendChild(style)

window.scrollIntoView(document.querySelector('#stream > li:nth-child(7) > article > div > span > a'));
```
