### ISSUE TITLE
Scrolling should not always break out of parent

### ISSUE THREAD

**Issue by charleshansen** [KoryNunn/scroll-into-view#6]
If the scrollable parent element is not window, you should have the option to only scroll the parent and not the window.

For example within a a list of elements for a dropdown I'd like to call scrollIntoView, but I would like the page to not also scroll when the list is in view.

We have a quick fix at https://github.com/pivotal-cf/scroll-into-view/commit/d0bee1632d923e973902e5f578e6f059e3d5caa7

This makes it never break out of the parent. You may not always want to do this, so we did not make a pull request.

**Comment by KoryNunn** [comment]
So you're after the ability to only scroll the targets closest scrollable parent?

I'll investigate adding this to the new settings.

**Comment by charleshansen** [comment]
Thanks for the quick response. It did the trick.
