### ISSUE TITLE
CHANGELOG missing

### ISSUE THREAD

**Issue by MichaelDeBoey** [KoryNunn/scroll-into-view#60]
I just saw the package is updated to `v1.9.4`, but I can't find any CHANGELOG to check out the changes.

Would you be so kind to provide us with a decent CHANGELOG please? 🙂

Thanks for all your hard work @KoryNunn! 🙂

**Comment by KoryNunn** [comment]
Hi, I'm not a huge fan of changelogs that are seperate from commit history, as you end up with a slightly wrong, often out of date version of reality.

Looking git log: https://github.com/KoryNunn/scroll-into-view/commits/master

you can see that the change tha caused the patch version bump was "Manual scroll should cancel/override scrollIntoView. Fixes #58." which links you to the code that changed, and the issue that was opened that prompted the change.

Another way to see all the changes is to use `git log` directly: `git log --oneline --decorate` which will print out everything that has happened, with version commits between changes.

I'm happy to be convinced, that at this point, I dont see the risk (wrong log, out of date, etc) as being worth the reward (curated version of git log)

**Comment by MichaelDeBoey** [comment]
@KoryNunn It would at least help to provide a change log with every release on the [releases page](https://github.com/KoryNunn/scroll-into-view/releases), but then you have to create git tags of course.

**Comment by KoryNunn** [comment]
Done.

https://github.com/KoryNunn/scroll-into-view/blob/master/CHANGELOG.md
