### ISSUE TITLE
Scrolling issues with overriden window.self property

### ISSUE THREAD

**Issue by joaomframos** [KoryNunn/scroll-into-view#70]
We are currently using scroll-into-view in a project that is deployed on top of several websites that are out of our control and we have recently discovered a situation where the window.self is being overriden by the client itself which leads to issues with the scroll.

We are still trying to figure out the reasoning behind this use-case but we were wondering about these changes:

https://github.com/korynunn/scroll-into-view/commit/f667da5456f8c1f58335a15aa13f700fd87bbbe5
https://github.com/korynunn/scroll-into-view/commit/307f257e23cd93541e1e2011278dfa51202b0a89

Would it be possibly to change the comparison to something like?
`window instanceof Window
`

**Comment by KoryNunn** [comment]
I would guess that somewhere they have a bug where they do `self = this` and forgot to use `var self`.

I would also guess that you could safely run `window.self = window` before calling `scrollIntoView()` to solve your issue.

I would recommend trying to fix broken code before looking to change correct code to circumvent broken code, but that being said, I'll see if there is a reasonable way to support this scenario.

**Comment by joaomframos** [comment]
One of the core principles of this app is that we do not interfere with websites (and their code) where our app is deployed.

Performing that change means that we are overriding a property that may be used by them and if their code is relying on that property, it will probably end up crashing their application once they attempt to use the 'expected' content from that variable.

I understand your frustration and also share your mindset. I have been trying to reach out to their development team in order to figure out a fix on their side but most of these companies either cannot request such a change to their IT department due to heavy work loads and scheduling or likely just paid an external company to setup their website and no longer have technical support. 

Either way, both situations are out of my reach. I'll keep on waiting for feedback from their end...

Meanwhile, I would like to know if you believe that such a change is viable.

**Comment by KoryNunn** [comment]
I have added the ability to provide a custom isWindow check: https://github.com/KoryNunn/scroll-into-view#how

I am pretty sad about this btw.
