### ISSUE TITLE
Too much recursion issue on some browsers

### ISSUE THREAD

**Issue by s-yadav** [KoryNunn/scroll-into-view#71]
The logic difference in 
https://github.com/KoryNunn/scroll-into-view/blob/master/scrollIntoView.js#L83
and 
https://github.com/KoryNunn/scroll-into-view/blob/master/scrollIntoView.js#L102
is causing too much recursion on some browsers. The reason is because of logic difference withing 1ms there can be lot many recursion and `endIterations` count will not be effective. 

Changing the condition to `time >= scrollSettings.time` should fix the issue.
```js
if(
        time >= scrollSettings.time &&
        scrollSettings.endIterations > 3
    ){
   ...
}
```

I can raise a PR, if the logic difference was not intentional.

**Comment by KoryNunn** [comment]
I believe the fix is simply to change https://github.com/KoryNunn/scroll-into-view/blob/master/scrollIntoView.js#L83

to `time >= scrollSettings.time &&`

Would it be possible for you to check if that solves your issue?

**Comment by KoryNunn** [comment]
I've published a new version that allows you to specify the max synchronous alignments that should address this issue. Let me know if there is still an issue.

**Comment by s-yadav** [comment]
Thanks for quick fix. I was not able to reproduce it by myself. But we were getting lot of this issue on sentry. After version upgrade I will monitor sentry for one day and will confirm you.
