### ISSUE TITLE
Failing to scroll towards direct children of body

### ISSUE THREAD

**Issue by joaomframos** [KoryNunn/scroll-into-view#73]
Have been noticing some weird scroll behaviours when an element is a direct child of the body but, as long as that element is wrapped inside a div everything works fine. 

Codesandbox of the broken example: https://codesandbox.io/s/loving-jepsen-5k3ib

Notice that it will scroll directly towards the bottom of the page, while the following scrolls directly to the element: https://codesandbox.io/s/laughing-sutherland-66qzs

There's only a small diference in the HTML file where the iframe is wrapped inside an empty div.

Unfortunately we are using this package directly webpages that we cannot control and I cannot simply change their HTML.

I managed to do some debugging and noticed that a simple change of order in the while(parent) loop, forcing the comparison with tagName 'body' to be ran first thing is enough to fix the issue.

As I am not aware of your current use cases, could this have any negative side effect?

**Comment by KoryNunn** [comment]
Did you want to send a PR with your changes to see how it runs in the tests?

**Comment by joaomframos** [comment]
The tests were all passing even with the change. Was just wondering if I could be missing something but I'll be submitting the PR shortly.
