### ISSUE TITLE
Ionic 4 not working

### ISSUE THREAD

**Issue by TravBradfield** [KoryNunn/scroll-into-view#75]
Hey man, 

I'm trying to scroll to an element in an *ngFor array. 
`
<ion-card *ngFor="let component of components; let i = index">
      <div id="{{ 'wave' + i }}"></div>
      <h1>{{ i }}</h1>
<ion-card>
`

And once that loads, I want to focus on an element in that list that's toward the bottom: 

`
import * as scrollElmIntoView from 'scroll-into-view';

 this.studyService.components$.subscribe((components: Array<StudyComponent>) => {
let TIME_IN_MS = 500;
 let timer= setTimeout(() => {
     let y = document.getElementById('wave8');
     console.log('Element y: ', y);
     scrollElmIntoView(y);
    }, TIME_IN_MS);
})
`

The correct element (y) is found and logged to the console, but no scrolling happens.

**Comment by KoryNunn** [comment]
Please put this just before your scrollElmIntoView(y); line:

```
console.log(y.getBoundingClientRect());
```

And let me know what it prints.

**Comment by TravBradfield** [comment]
Thanks very much! I will give that a try today!

**Comment by TravBradfield** [comment]
DOMRect {x: 10, y: 13251.453125, width: 707, height: 0, top: 13251.453125, …}
bottom: 13251.453125
height: 0
left: 10
right: 717
top: 13251.453125
width: 707
x: 10
y: 13251.453125
__proto__: DOMRect

**Comment by KoryNunn** [comment]
That looks fine to me so I've added a debug flag in the settings that you can use to get some logs to help you track down what's happening

Just set `debug: true` in the settings and let me know what gets logged (feel free to obfuscate any sensitive data)

**Comment by KoryNunn** [comment]
The latest version (v1.14.1) support shadow-dom traversal, which might have been what was required to solve this issue as the latest ionic uses shadow-dom.

Please give it a go, and if there are still issues feel free to re-open this issue.
