### ISSUE TITLE
Element at bottom of container does not scroll into view with topOffset

### ISSUE THREAD

**Issue by gavrielco** [KoryNunn/scroll-into-view#78]
When the target element is at the bottom of its parent container and a `topOffset` is passed in the `align` options, then the parent container is not scrolled to the bottom but instead is scrolled to `topOffset` from the bottom - leaving the target element out of view.

Here is an example: https://codepen.io/gavri/pen/XWJNXaQ

**Comment by KoryNunn** [comment]
Resolved by #80
