### ISSUE TITLE
Textdirection (rtl) has no scrolling 

### ISSUE THREAD

**Issue by axcr** [KoryNunn/scroll-into-view#87]
Thx a lot for your package work - it's really helpful, but i think there is a little issue with text directions, particular rtl (right-to-left) has no scrolling on Safari Desktop.

**Comment by KoryNunn** [comment]
I'd love for someone to create a failing test for this, but It's not something I can easily do my self.

Given that this issue has been open for over a year without further discussion, I'll close it for now. Feel free to re-open or start a new issue if there's still a problem
