### ISSUE TITLE
Only y-axis scrolling

### ISSUE THREAD

**Issue by alexvandervegt** [KoryNunn/scroll-into-view#88]
Is it possible to block the scroller to also scroll horizontal?

Now sometimes my pages get messed up because the whole site is scrolled to the left where i only want to scroll to the bottom of a page.

I already tried align.left: 0

But this is not working

**Comment by KoryNunn** [comment]
Hey, yes scroll-into-view will align horizontally, you can see an example of this working in the example: http://korynunn.github.io/scroll-into-view/example/

I would guess that you are targeting an element that is the full width of your page. You might want to target a smaller/more specific element.

**Comment by KoryNunn** [comment]
Closing this for now, feel free to re-open if there is anything more you want to add.
