### ISSUE TITLE
[Gratitude] Thank You So Much!

### ISSUE THREAD

**Issue by loganknecht** [KoryNunn/scroll-into-view#92]
Hey!

I just wanted to reach out and say thank you so much for this library!

I've been having a huge headache trying to get a feature in my codebase with just the right implementation, but with your library's help I was able to do it!

I donated some money, because for real - thank you. You've solved an incredibly annoying problem I had scrolling, and it works with literally no friction.

Follow up feature requests might be:
- Scrolling to an element within a set of specified containers that are also scrollable

Thank you again! I really appreciate this library and your efforts!

**Comment by KoryNunn** [comment]
Thanks for the feedback!

As for the feature request, if what you're trying to do is avoid scrolling certain elements, that's already possible using the isScrollable function:

```
    isScrollable: function(target, defaultIsScrollable){

        // By default scroll-into-view will only attempt to scroll elements that have overflow not set to `"hidden"` and who's scroll width/height is larger than their client height.
        // You can override this check by passing an `isScrollable` function to settings:

        return defaultIsScrollable(target) || ~target.className.indexOf('scrollable');
    },
```

Just return false for any element you want skipped.

**Comment by loganknecht** [comment]
Wow! @KoryNunn - that was the ticket!

I cannot believe how amazing this library is!

I ended up opting for a solution like this, because I kept getting `undefined` `className`/`classList` errors. But darn it, it works!

```typescript
const scrollBarCheck = (target: undefined | HTMLElement, defaultIsScrollable: any) => {
    if (target !== null && target !== undefined) {
        const is_nested_scroll_view =
            "classList" in target && target.classList.contains("NestedScrollView") ? true : false;
        const is_parent_scroll_view = target.id === "ParentScrollView";

        const is_element_that_should_be_scrolled = is_nested_scroll_view || is_parent_scroll_view;

        return is_element_that_should_be_scrolled;
    } else {
        return false;
    }
};
const scroll_options = {
    isScrollable: sheetMusicCursorScrollBarCheck,
};
scrollIntoView(sheet_music_cursor_element, scroll_options as any, onComplete);
```

You are literally the best! I'm so happy I could be one of your first contributors! And thank you for even providing a response with how to achieve what I was looking for! 😄
