### ISSUE TITLE
"scrolling done" callback function not getting called

### ISSUE THREAD

**Issue by davidjpfeiffer** [KoryNunn/scroll-into-view#93]
The third parameter of the scrollIntoView object is a callback function documented at https://www.npmjs.com/package/scroll-into-view which is supposed to "be called when all scrolling has been completed or canceled".

The callback function I am providing is not getting called, even though the scrolling has completed.

By the way, this is the best scrolling library I have found on NPM! Great work! Thank you!

**Comment by KoryNunn** [comment]
Hey, thanks for the issue

Are you able to provide a failing test case?

There are passing tests for this, for example, here: https://github.com/KoryNunn/scroll-into-view/blob/master/test/test.js#L370

**Comment by KoryNunn** [comment]
Closing due to no info
