### ISSUE TITLE
Scrolling is ignoring anti scrolling CSS rules in body

### ISSUE THREAD

**Issue by joaomframos** [KoryNunn/scroll-into-view#94]
Created a simple example to verify the issue:
https://codesandbox.io/s/sleepy-bash-56vi0?file=/src/App.js

Body has an overflow: hidden but the way the scrolling behaves, especially the part that skips from the body to the window, behaves in such a way that the body rule are completely discarded. 

Also, while testing out the example case, noticed a minor 'error' with the docs. If the isScrollable is being used and it's possible to hit the window, using the className should not be recommended.

**Comment by KoryNunn** [comment]
Hi, thanks for the issue.

I agree that the docs should be updated to show that you cant treat all scroll targets as elements, given that the top-most will be Window, I'll fix that shortly.

I can't see the other issue you mentioned, as the codesandbox link just logs the error, and doesn't scroll. If it scrolls for you, what browser are you using? Otherwise, would you be able to give me a reproduction of just the bug you've mentioned?

**Comment by joaomframos** [comment]
Apparently I had a few issues with that version of the code... Here's the updated one: https://codesandbox.io/s/pensive-varahamihira-wyb57
The problem lies with the body's style: overflow is hidden and unless I completely misunderstood your point regarding the 'isScrollable' option, the scroll should not happen. Try to scroll the page manually. You shouldnt be able to (unless I fucked up again, my bad) but if you click the text on top that triggers the scroll, the scroll will happen.

Docs state that 'By default scroll-into-view will only attempt to scroll elements that have overflow not set to `"hidden"`' .

**Comment by KoryNunn** [comment]
It's not the <body> that's scrolling in that example, it's the <html>.

You can inspect the elements and check their scrollTop. for body, it remains 0, for html, it's some value > 0.

**Comment by KoryNunn** [comment]
if you want to prevent `window` from scrolling, use a custom `isScrollable` function the returns `false` when it is given `window`

**Comment by joaomframos** [comment]
You are completely right. I assumed that it was an issue with skipping the body but it didn't matter as the one scrolling was the window. Made the change on my end and work as intended. Thank you for all the help.
