### ISSUE TITLE
IE 11 - cannot use arrow function (syntax error)

### ISSUE THREAD

**Issue by adrian-huminiuc** [KoryNunn/scroll-into-view#95]
Hey, any chance we can have the arrow function from the last reduce() into a normal function() {}. 
Would help out and eliminate a syntax error on ie 11

**Comment by KoryNunn** [comment]
Hi,

You can trivially support any browser by building scroll-into-view with babel and targeting legacy browsers.

I do not want to add support for browsers that are themselves nearly [out of support from Microsoft](https://www.zdnet.com/article/microsoft-sets-deadline-for-end-of-support-of-ie-11-by-365-apps/)
