### ISSUE TITLE
v1.16.0 no longer works in IE 11

### ISSUE THREAD

**Issue by trm217** [KoryNunn/scroll-into-view#97]
## Description

In v1.16.0 an arrow function (es6) was added to the scrollIntoView.js file on line 275.
Since the code isn't compiled into es5, this change caused sites to no longer work with IE 11.

Perhaps it would make sense to add Bable, in order to compile es6 syntax, which is used in a few places from what I see (mainly in tests and example files as of now), to prevent such problems from occurring in the future.

**Comment by KoryNunn** [comment]
Hi, please see this previous issue on IE support: https://github.com/KoryNunn/scroll-into-view/issues/95

TL;DR: You can use babel if you need to support a browser that the manufacturer themselves doesn't support, but it's not the job of scroll-into-view to do that.
