### ISSUE TITLE
Version 1.16.0 broke IE11 compatibility

### ISSUE THREAD

**Issue by robinchesterman** [KoryNunn/scroll-into-view#99]
Line 165 uses ES6 property value shorthand, which IE11 will not understand:

```
        maxSynchronousAlignments: maxSynchronousAlignments,
        end: end,
        scrollAncestor
```

This could be fixed with `scrollAncestor: scrollAncestor`

**Comment by KoryNunn** [comment]
Hi, please see this previous issue on IE support: #97 

TL;DR: You can use babel if you need to support a browser that the manufacturer themselves doesn't support, but it's not the job of scroll-into-view to do that.

**Comment by robinchesterman** [comment]
Thanks for the reply. I understand your reasons. The only comment I would add is that:

- IE isn't going away _quite_ yet! [see here](https://techcommunity.microsoft.com/t5/windows-it-pro-blog/internet-explorer-11-desktop-app-retirement-faq/ba-p/2366549)
- It's common for many projects to exclude transpilation of node modules due to the significant impact it can have on build time
- It's such a tiny fix

But I understand. :)
